## T Test
Inferential stastic used to determine if there between the means of two groups/distribution.

It's of two types: 
1. One-sampled T-test - The test will tell us whether the means of the sample and the population are different.
2. Two-sampled T-test - The test compares the means of two independent groups in order to determine whether their associated population means are different.



**ONE SAMPLED T-TEST**

In [ ]:
from numpy.random import seed
from numpy.random import randn
#Suppose a society 1 of people with the following ages are listed.
seed(1)
ages1 = 0.5 * randn(100) + 25

In [ ]:
#The size of population:
#The number of people in society 1:
len(ages1)

46

In [ ]:
#Checking if the ages1 population is Gaussian or not
from scipy.stats import normaltest
stat, p=normaltest(ages1)
alpha=0.1
if p>alpha:
  print("Slope is Gaussian")
else:
  print("Slope is not Gaussian")

Slope is Gaussian


In [ ]:
#Finding mean of the ages in society 1. This is also the population mean of society 1
import numpy as np
ages1_mean=np.mean(ages1)
ages1_mean

25.030291426037852

In [ ]:
#Considering a sample of the population with n=15 in society 1
sample_size=15
ages1_sample=np.random.choice(ages1,sample_size)
ages1_sample

array([24.57739718, 24.73591412, 25.09914986, 25.20502582, 25.06007948,
       24.89555288, 24.65641365, 24.86605596, 25.2933116 , 25.0932807 ,
       24.80162324, 24.86605596, 25.21174718, 25.15781747, 25.15951955])

In [ ]:
from scipy.stats import ttest_1samp
#Null Hypothesis: The sample mean of ages in society 1 is equal to population mean in society 1
#Alternate Hypothesis: The sample mean of ages is different from population mean of ages

In [ ]:
#We are comparing the sample of ages1 with the mean of population of ages1
ttest_1samp,p_value=ttest_1samp(ages1_sample, ages1_mean)
print(p_value)

0.3827441716604686


If the resulting p-value is less than alpha, then the difference between both observations is statistically significant, and the null hypothesis is rejected.



The level of significance or alpha is the probability of incorrectly concluding that the null hypothesis is false. The significance value used in a one-tailed test is either 1%, 5% or 10% usually. We are considering all these cases.

In [ ]:
# Interpretating with alpha=0.05. Case 1: n=15 and alpha=0.05
alpha = 0.05
if p_value < alpha:    # alpha value is 0.05 or 5%
    print("We are rejecting null hypothesis. Reject H0")
else:
    print("We are accepting null hypothesis. Accept H0")

We are accepting null hypothesis. Accept H0


When alpha-value = 0.05, or 5%, we can be 95% confident that the population mean is equal to the sample mean. We will therefore accept H0 and support the claim that the sample mean is equal to poulation mean. The p-value is 0.38 while alpha value is 0.05.

In [ ]:
# Interpretating with alpha=0.01. Case 2: n=15 and alpha=0.01 
alpha = 0.01
if p_value < alpha:    # alpha value is 0.01 or 1%
    print("We are rejecting null hypothesis. Reject H0")
else:
    print("We are accepting null hypothesis. Accept H0")

We are accepting null hypothesis. Accept H0


When alpha-value = 0.01, or 1%, we can be 99% confident that the population mean is equal to the sample mean. We will therefore accept H0 and support the claim that the sample mean is equal to poulation mean. There is still 1% chance that our claim is false. And H1 that is the sample mean is not actually equal to population mean but that chance is really low. This is actually the slim tail part which has 0.005 on both sides of the graph since this is a doubled-tail T test. The p-value is 0.38 while alpha value is 0.01.

In [ ]:
# Interpretating with alpha=0.1. Case 3: n=15 and alpha=0.1
alpha = 0.10
if p_value < alpha:    # alpha value is 0.10 or 10%
    print("We are rejecting null hypothesis. Reject H0")
else:
    print("We are accepting null hypothesis. Accept H0")

We are accepting null hypothesis. Accept H0


When alpha-value = 0.1, or 10%, we can be 90% sure that the population mean is equal to the sample mean. We will therefore accept H0 and support the claim that the sample mean is equal to poulation mean. The p-value is 0.38 while alpha value is 0.1.

In [ ]:
#Considering a sample of the population with n=35 in society 1
sample_size=35
ages1_sample=np.random.choice(ages1,sample_size)
ages1_sample

array([25.34901602, 24.65641365, 25.15951955, 25.09914986, 25.41398732,
       25.15008516, 25.38100559, 24.55618552, 25.24425907, 25.20502582,
       25.45042797, 24.44969041, 25.02540388, 24.45005437, 24.65416962,
       25.09257821, 25.56688472, 25.29140761, 24.93855489, 24.66466886,
       24.61939655, 25.34901602, 24.82532864, 26.05012757, 24.62280103,
       24.66437693, 24.65641365, 25.29140761, 25.75990841, 25.45042797,
       25.20502582, 25.21174718, 25.82990109, 26.05012757, 23.84923065])

In [ ]:
from scipy.stats import ttest_1samp
#Null Hypothesis: The sample mean of ages in society 1 is equal to population mean in society 1
#Alternate Hypothesis: The sample mean of ages is different from population mean of ages

#We are comparing the sample of ages1 with the mean of population of ages1.
#Instead of taking the given population mean, let's have a variation and take an assumed population mean ages2_mean=45.
ages2_mean=45
ttest_1samp,p_value=ttest_1samp(ages1_sample, ages2_mean)
print(p_value)

9.688161152711421e-57


If the resulting p-value is less than 5%, then the difference between both observations is statistically significant, and the null hypothesis is rejected. 

The level of significance or alpha is the probability of incorrectly concluding that the null hypothesis is false. The significance value used in a one-tailed test is either 1%, 5% or 10% usually. We are considering all these cases.

In [ ]:
# Interpretating with alpha=0.05. Case 4: n=35 and alpha=0.05.
# We here took a different assumed mean and not the actual population mean to study the variation.
alpha = 0.05
if p_value < alpha:    # alpha value is 0.05 or 5%
    print("We are rejecting null hypothesis. Reject H0")
else:
    print("We are accepting null hypothesis. Accept H0")

We are rejecting null hypothesis. Reject H0


When alpha-value = 0.05, or 5%, we can be 95% confident that the population mean is not equal to the sample mean. We will therefore reject H0 and support the claim that the sample mean is not equal to the assumed poulation mean. 

In [ ]:
# Interpretating with alpha=0.01. Case 6: n=35 and alpha=0.01.
# We here took a different assumed mean and not the actual population mean to study the variation.
alpha = 0.01
if p_value < alpha:    # alpha value is 0.01 or 1%
    print("We are rejecting null hypothesis. Reject H0")
else:
    print("We are accepting null hypothesis. Accept H0") 

We are rejecting null hypothesis. Reject H0


When alpha-value = 0.01, or 1%, we can be 99% confident that the population mean is not equal to the sample mean. We will therefore reject H0 and support the claim that the sample mean is not equal to the assumed poulation mean. 

In [ ]:
# Interpretating with alpha=0.10. Case 5: n=35 and alpha=0.1.
# We here took a different assumed mean and not the actual population mean to study the variation.
alpha = 0.10
if p_value < alpha:    # alpha value is 0.10 or 10%
    print("We are rejecting null hypothesis. Reject H0")
else:
    print("We are accepting null hypothesis. Accept H0") 

We are rejecting null hypothesis. Reject H0


When alpha-value = 0.1, or 10%, we can be 90% confident that the population mean is not equal to the sample mean. We will therefore reject H0 and support the claim that the sample mean is not equal to the assumed poulation mean. 

**TWO SAMPLED T-TEST**

In [ ]:
#Suppose two societies of people with the following ages listed.

In [ ]:
from numpy.random import seed
from numpy.random import randn

In [ ]:
#seed the random number generator
seed(1)
# generate two independent samples
ages1 = 0.5 * randn(100) + 25
ages2 = 0.5 * randn(90) + 28

In [ ]:
#The number of people in society1:
len(ages1)

100

In [ ]:
#The number of people in society2:
len(ages2)

90

In [ ]:
#Finding mean of the ages in society 1:
import numpy as np
ages1_mean=np.mean(ages1)
ages1_mean

25.030291426037852

In [ ]:
#Finding mean of the ages in society 2:
ages2_mean=np.mean(ages2)
ages2_mean

28.04902402423229

In [ ]:
#Considering a sample of the population with n=15 in society 1
sample_size=15
ages1_sample=np.random.choice(ages1,sample_size)
ages1_sample

array([24.44134483, 25.09545774, 24.88883593, 24.53211528, 25.08001853,
       24.86605596, 24.73591412, 25.34901602, 24.80797282, 24.55618552,
       24.44134483, 24.90408222, 25.02110687, 25.02179843, 25.82990109])

In [ ]:
ages2_sample=np.random.choice(ages2,sample_size)
ages2_sample

array([27.85167942, 28.03891056, 27.96344365, 28.20174582, 27.40036598,
       28.34003492, 27.88684288, 28.0087047 , 28.43444308, 28.81382538,
       27.61241919, 28.0087047 , 27.98065225, 27.42782931, 28.1575797 ])

In [ ]:
# summarize to conclude they are from different populations
print('Ages of society 1: mean=%.3f stdv=%.3f' % (np.mean(ages1), np.std(ages1)))
print('Ages of society 2: mean=%.3f stdv=%.3f' % (np.mean(ages2), np.std(ages2)))

Ages of society 1: mean=25.030 stdv=0.443
Ages of society 2: mean=28.049 stdv=0.461


In [ ]:
from scipy.stats import ttest_ind
#Null Hypothesis or H0: The population mean of ages in society 1 is equal to population mean of ages in society 2
#Alternate Hypothesis or H1: The population mean of ages in both the societies are different

In [ ]:
stat, p = ttest_ind(ages1_sample, ages2_sample)
print('Statistics=%.2f, p=%.2f' % (stat, p))

Statistics=-23.12, p=0.00


If the resulting p-value is less than alpha, then the difference between both observations is statistically significant, and the null hypothesis is rejected.

In [ ]:
# Interpretating with alpha=0.05. Case 1: alpha=0.05, n=15
alpha = 0.05
if p < alpha:    # alpha value is 0.05 or 5%
    print("We are rejecting null hypothesis. Reject H0. It means there is a significant difference between the means of the two population.")
else:
    print("We are accepting null hypothesis. Accept H0")

We are rejecting null hypothesis. Reject H0. It means there is a significant difference between the means of the two population.


When alpha-value = 0.05, or 5%, we can be 95% confident that the sample mean of society 1 is not equal to the sample mean of society 2. We will therefore reject H0 and support the claim that the both the sample means are from significantly different populations. Here p=0.0 while alpha=0.05

In [ ]:
# Interpretating with alpha=0.01. Case 2: alpha=0.01, n=15
alpha = 0.01
if p < alpha:    # alpha value is 0.01 or 1%
    print("We are rejecting null hypothesis. Reject H0. It means there is a significant difference between the means of the two population.")
else:
    print("We are accepting null hypothesis. Accept H0")

We are rejecting null hypothesis. Reject H0. It means there is a significant difference between the means of the two population.


When alpha-value = 0.01, or 1% , we can be 99% confident that the population mean of society 1 is not equal to the population mean of society 2. We will therefore reject H0 and support the claim that the both the sample means are not from significantly different populations. Here p=0.0 while alpha=0.01. We are accepting H1 or the alternate hypothesis.

In [ ]:
# Interpretating with alpha=0.1. Case 3: alpha=0.01, n=15
alpha = 0.1
if p < alpha:    # alpha value is 0.1 or 10%
    print("We are rejecting null hypothesis. Reject H0. It means there is a significant difference between the means of the two population.")
else:
    print("We are accepting null hypothesis. Accept H0. They belong to same population or with there is no significant difference between the means of two population.")

We are rejecting null hypothesis. Reject H0. It means there is a significant difference between the means of the two population.


When alpha-value = 0.1, or 10% or more, we can be 90% sure that the population mean of society 1 is not equal to the population mean of society 2. We will therefore accept H1 and support the claim that  they belong to same population or with there is significant difference between the means of two population. Though there is still 10% chance that our rejection of the null hypothesis is wrong.

Which was not the situation in this case when we tested the mean of the two population distributions at alpha = 0.01 or 0.05.

In [ ]:
#Considering a sample of the population with n=35 in society 1
sample_size=35
ages1_sample=np.random.choice(ages1,sample_size)
ages1_sample

array([25.45079536, 25.87240588, 24.82807316, 25.56688472, 25.18878189,
       23.98889939, 24.9936677 , 24.85095358, 24.65641365, 25.09257821,
       25.30860155, 25.81217268, 25.45079536, 25.02179843, 24.2779431 ,
       24.44134483, 25.02110687, 24.53211528, 24.86605596, 24.4287409 ,
       25.21174718, 25.15008516, 25.09545774, 24.61939655, 25.05950432,
       24.9137859 , 25.26517773, 23.96992965, 25.62643408, 25.56688472,
       24.65416962, 25.15951955, 24.90408222, 25.06007948, 24.65416962])

In [ ]:
ages2_sample=np.random.choice(ages2,sample_size)
ages2_sample

array([28.98355087, 28.49316759, 28.24760566, 28.42308032, 27.19211382,
       28.27526875, 27.31344134, 27.40036598, 27.88684288, 28.08469122,
       28.15677386, 28.08469122, 28.43444308, 28.28138055, 28.5194123 ,
       27.94047291, 27.93177763, 28.34003492, 28.12036855, 28.15677386,
       27.31344134, 29.26416285, 28.11624728, 28.20445027, 28.42308032,
       28.61808202, 27.85634607, 27.98065225, 27.45254408, 28.14033254,
       28.16900585, 27.84494161, 29.09534986, 28.29678926, 28.0087047 ])

In [ ]:
# summarize to conclude they are from different populations
print('Ages of society 1: mean=%.3f stdv=%.3f' % (np.mean(ages1), np.std(ages1)))
print('Ages of society 2: mean=%.3f stdv=%.3f' % (np.mean(ages2), np.std(ages2)))

Ages of society 1: mean=25.030 stdv=0.443
Ages of society 2: mean=28.049 stdv=0.461


In [ ]:
from scipy.stats import ttest_ind
#Null Hypothesis or H0: The population mean of ages in society 1 is equal to population mean of ages in society 2
#Alternate Hypothesis or H1: The population mean of ages in both the societies are different
stat, p = ttest_ind(ages1_sample, ages2_sample)
print('Statistics=%.2f, p=%.2f' % (stat, p))

Statistics=-28.47, p=0.00


In [ ]:
# Interpretating with alpha=0.05. Case 4: alpha=0.05 n=35
alpha = 0.05
if p < alpha:    # alpha value is 0.05 or 5%
    print("We are rejecting null hypothesis. Reject H0. It means there is a significant difference between the means of the two population.")
else:
    print("We are accepting null hypothesis. Accept H0")

We are rejecting null hypothesis. Reject H0. It means there is a significant difference between the means of the two population.


When alpha-value = 0.05, or 5%, we can be 95% confident that the sample mean of society 1 is not equal to the sample mean of society 2. We will therefore reject H0 and support the claim that the both the sample means are from significantly different populations. 

In [ ]:
# Interpretating with alpha=0.01. Case 2: alpha=0.01, n=15
alpha = 0.01
if p < alpha:    # alpha value is 0.01 or 1%
    print("We are rejecting null hypothesis. Reject H0. It means there is a significant difference between the means of the two population.")
else:
    print("We are accepting null hypothesis. Accept H0")

We are rejecting null hypothesis. Reject H0. It means there is a significant difference between the means of the two population.


When alpha-value = 0.01, or 1%, we can be 99% confident that the sample mean of society 1 is not equal to the sample mean of society 2. We will therefore reject H0 and support the claim that the both the sample means are from significantly different populations. 

In [ ]:
# Interpretating with alpha=0.1. Case 3: alpha=0.01, n=15
alpha = 0.1
if p < alpha:    # alpha value is 0.1 or 10%
    print("We are rejecting null hypothesis. Reject H0. It means there is a significant difference between the means of the two population.")
else:
    print("We are accepting null hypothesis. Accept H0. They belong to same population or with there is no significant difference between the means of two population.")

We are rejecting null hypothesis. Reject H0. It means there is a significant difference between the means of the two population.


When alpha-value = 0.1, or 10% or more, we can be 90% sure that the population mean of society 1 is not equal to the population mean of society 2. We will therefore reject H0 and support the claim that they don't belong to same population or with significant difference between the means of two population. Though there is still 10% chance that our reject the null hypothesis is wrong.

**PAIRED T-TEST**

This is done to compare the samples from the same group.
Because the samples are not independent, we cannot use the Student’s t-test. Instead, we must use a modified version of the test that checks for the fact that the data samples are dependent, called the paired Student’s t-test.

In the example from the website, they have taken there samples to be independent, not paired, we can pretend for the sake of the demonstration that the observations are paired and calculate the statistic.

But in this example, we will take samples that are actually paired.

Assume a class of students with weight 1 in 6th standard. Their height rose on a  with a location parameter of 0.5 and a scale parameter of 5. The size parameter is based on the lenth of weight 1. 

It is after a few years that their weight is remeasured and it showed the changes in weight 2. 

The effect of the location parameter is to translate the graph, relative to the standard normal distribution, 0.5 units to the right on the horizontal axis.

The effect of a scale parameter more than one is to decompress the pdf. 

In [ ]:
# seed the random number generator
seed(1)
# generate two independent samples
weight1 = 0.5 * randn(24) + 35
len(weight1)

24

In [ ]:
print(weight1)

[35.81217268 34.69412179 34.73591412 34.46351569 35.43270381 33.84923065
 35.87240588 34.61939655 35.15951955 34.87531481 35.73105397 33.96992965
 34.8387914  34.80797282 35.56688472 34.45005437 34.9137859  34.56107079
 35.02110687 35.29140761 34.44969041 35.57236185 35.45079536 35.25124717]


In [ ]:
import scipy.stats as stats
weight2=weight1+stats.norm.rvs(scale=5,loc=0.5,size=24)

In [ ]:
print(weight2)

[40.81645243 31.7754825  34.621463   30.28466852 34.59326342 37.00100799
 32.91410212 33.13562892 32.22365605 31.1492866  32.87482331 34.40660665
 29.75223965 36.48005131 44.36589561 38.66027517 34.45460813 30.62292597
 31.7853154  44.25368061 35.20372919 32.88738362 36.90537278 46.25252285]


In [ ]:
#Considering a sample of the population with n=15 in weight1 and weight2
sample_size=15
weight1_sample=np.random.choice(weight1,sample_size)
weight1_sample
weight2_sample=np.random.choice(weight2,sample_size)
weight2_sample

array([34.45460813, 31.7853154 , 40.81645243, 36.48005131, 32.87482331,
       46.25252285, 30.62292597, 33.13562892, 32.87482331, 35.20372919,
       40.81645243, 29.75223965, 31.7754825 , 31.1492866 , 31.7853154 ])

In [ ]:
#Comparing weights in 6th and 8th standard respectively. Seeing first 10 records.
import pandas as pd

weight_df=pd.DataFrame({"Weight_6":np.array(weight1_sample),"Weight_8":np.array(weight2_sample), "Weight_Change":np.array(weight2_sample)-np.array(weight1_sample)})
weight_df.head(10)

Weight_6   Weight_8  Weight_Change
0  34.838791  34.454608      -0.384183
1  35.572362  31.785315      -3.787046
2  33.969930  40.816452       6.846523
3  34.619397  36.480051       1.860655
4  34.807973  32.874823      -1.933150
5  35.159520  46.252523      11.093003
6  33.969930  30.622926      -3.347004
7  34.838791  33.135629      -1.703162
8  33.969930  32.874823      -1.095106
9  34.449690  35.203729       0.754039

In [ ]:
#Null Hypothesis: The sample mean of weight1 population is equal to sample mean of weight2 population
#Alternate Hypothesis: The sample mean of weight1 is different from sample mean of weight2

In [ ]:
# compare samples weight 1 and weight 2
from scipy.stats import ttest_rel
stat, p = ttest_rel(weight1_sample, weight2_sample)
print('Statistics=%.3f, p=%.3f' % (stat, p))

Statistics=0.075, p=0.941


In [ ]:
# Interpretating with alpha=0.05. Case 1: alpha=0.05, n=15
alpha = 0.05
if p < alpha:    # alpha value is 0.05 or 5%
    print("We are rejecting null hypothesis. Reject H0. It means there is a significant difference between the means of the two population.")
else:
    print("We are accepting null hypothesis. Accept H0. It means there is not much difference between the recent weight and previous weight of the group")

We are accepting null hypothesis. Accept H0. It means there is not much difference between the recent weight and previous weight of the group


When alpha-value = 0.05, or 5%, we can be 95% confident that the population mean of the two weights are same. We will therefore accept H0 and support the claim. It means there is not much difference between the samples of recent weight and samples of previous weight of the group. The p=0.94 while alpha=0.05

In [ ]:
# Interpretating with alpha=0.10. Case 2: alpha=0.10, n=15
alpha = 0.10
if p < alpha:    # alpha value is 0.10 or 10%
    print("We are rejecting null hypothesis. Reject H0. It means there is a significant difference between the means of the two population.")
else:
    print("We are accepting null hypothesis. Accept H0. It means there is not much difference between the recent weight and previous weight of the group")

We are accepting null hypothesis. Accept H0. It means there is not much difference between the recent weight and previous weight of the group


When alpha-value = 0.10, or 10%, we can be 90% confident that the population mean of the two weights are same. We will therefore accept H0 and support the claim.

There is still 10% chance that our claim is wrong and these two weights have significant difference. It means there is not much difference between the samples of recent weight and samples of previous weight of the group. or there is a close relationship between the two weights. The p=0.94 while alpha=0.10.

In [ ]:
# Interpretating with alpha=0.01. Case 3: alpha=0.01, n=15
alpha = 0.01
if p < alpha:    # alpha value is 0.01 or 1%
    print("We are rejecting null hypothesis. Reject H0. It means there is a significant difference between the means of the two population.")
else:
    print("We are accepting null hypothesis. Accept H0. It means there is not much difference between the recent weight and previous weight of the group")

We are accepting null hypothesis. Accept H0. It means there is not much difference between the recent weight and previous weight of the group


When alpha-value = 0.01, or 1%, we can be 99% confident that the population mean of the two weights are same. We will therefore accept H0 and support the claim.

There is still 1% chance that our claim is wrong and these two weights have significant difference. Though it is very little that such an error will occur.

In [ ]:
#Considering a sample of the population with n=35 in weight1 and weight2
sample_size=35
weight1_sample=np.random.choice(weight1,sample_size)
weight1_sample
weight2_sample=np.random.choice(weight2,sample_size)
weight2_sample

array([46.25252285, 32.88738362, 33.13562892, 40.81645243, 44.25368061,
       30.62292597, 44.36589561, 36.48005131, 35.20372919, 35.20372919,
       34.40660665, 32.91410212, 36.48005131, 38.66027517, 31.1492866 ,
       34.621463  , 33.13562892, 32.88738362, 37.00100799, 34.59326342,
       37.00100799, 32.88738362, 32.22365605, 36.48005131, 30.62292597,
       30.62292597, 38.66027517, 36.48005131, 32.22365605, 44.36589561,
       36.48005131, 46.25252285, 34.45460813, 32.87482331, 36.48005131])

In [ ]:
#Comparing weights in 6th and 8th standard respectively. Seeing first 10 records.
import pandas as pd

weight_df=pd.DataFrame({"Weight_6":np.array(weight1_sample),"Weight_8":np.array(weight2_sample), "Weight_Change":np.array(weight2_sample)-np.array(weight1_sample)})
weight_df.head(10)

Weight_6   Weight_8  Weight_Change
0  35.291408  46.252523      10.961115
1  34.694122  32.887384      -1.806738
2  34.735914  33.135629      -1.600285
3  34.838791  40.816452       5.977661
4  34.619397  44.253681       9.634284
5  34.735914  30.622926      -4.112988
6  35.731054  44.365896       8.634842
7  35.450795  36.480051       1.029256
8  35.812173  35.203729      -0.608443
9  34.875315  35.203729       0.328414

In [ ]:
#Null Hypothesis: The sample mean of weight1 population is equal to sample mean of weight2 population
#Alternate Hypothesis: The sample mean of weight1 is different from sample mean of weight2

In [ ]:
# compare samples weight 1 and weight 2
from scipy.stats import ttest_rel
stat, p = ttest_rel(weight1_sample, weight2_sample)
print('Statistics=%.3f, p=%.3f' % (stat, p))

Statistics=-1.468, p=0.151


In [ ]:
# Interpretating with alpha=0.05. Case 4: alpha=0.05, n=35
alpha = 0.05
if p < alpha:    # alpha value is 0.05 or 5%
    print("We are rejecting null hypothesis. Reject H0. It means there is a significant difference between the means of the two population.")
else:
    print("We are accepting null hypothesis. Accept H0. It means there is not much difference between the recent weight and previous weight of the group")

We are accepting null hypothesis. Accept H0. It means there is not much difference between the recent weight and previous weight of the group


When alpha-value = 0.05, or 5%, we can be 95% confident that the population mean of the two weights are same. We will therefore accept H0 and support the claim. It means there is not much difference between the samples of recent weight and samples of previous weight of the group. 

In [ ]:
# Interpretating with alpha=0.10. Case 5: alpha=0.10, n=35
alpha = 0.10
if p < alpha:    # alpha value is 0.10 or 10%
    print("We are rejecting null hypothesis. Reject H0. It means there is a significant difference between the means of the two population.")
else:
    print("We are accepting null hypothesis. Accept H0. It means there is not much difference between the recent weight and previous weight of the group")

We are accepting null hypothesis. Accept H0. It means there is not much difference between the recent weight and previous weight of the group


When alpha-value = 0.10, or 10%, we can be 90% confident that the population mean of the two weights are same. We will therefore accept H0 and support the claim.

There is still 10% chance that our claim is wrong and these two weights have significant difference. It means there is not much difference between the samples of recent weight and samples of previous weight of the group. or there is a close relationship between the two weights.


In [ ]:
# Interpretating with alpha=0.01. Case 6: alpha=0.01, n=35
alpha = 0.01
if p < alpha:    # alpha value is 0.01 or 1%
    print("We are rejecting null hypothesis. Reject H0. It means there is a significant difference between the means of the two population.")
else:
    print("We are accepting null hypothesis. Accept H0. It means there is not much difference between the recent weight and previous weight of the group")

We are accepting null hypothesis. Accept H0. It means there is not much difference between the recent weight and previous weight of the group


When alpha-value = 0.01, or 1%, we can be 99% confident that the population mean of the two weights are same. We will therefore accept H0 and support the claim.

There is still 1% chance that our claim is wrong and these two weights have significant difference. Though it is very little that such an error will occur.


**Creating the independent T-test from scratch** 

In [ ]:
#Suppose two societies of people with the following ages listed.
# seed the random number generator
seed(1)
# generate two independent samples
ages1 = 0.5 * randn(46) + 25
ages2 = 0.5 * randn(53) + 28

In [ ]:
#The number of people in society1:
len(ages1)

46

In [ ]:
#The number of people in society2:
len(ages2)

53

In [ ]:
#Importing necessary libraries
import numpy as np
from math import sqrt
from scipy.stats import sem
from scipy.stats import t

In [ ]:
#Form samples of size=20 for ages1 and ages2 to t-test
sample_size=20
ages1_sample=np.random.choice(ages1,sample_size)
ages1_sample

array([24.57739718, 24.73591412, 24.44969041, 25.29140761, 24.65641365,
       24.86605596, 25.02110687, 24.80162324, 24.86605596, 24.65416962,
       25.73105397, 25.15951955, 24.68150218, 24.9936677 , 24.65641365,
       25.15951955, 24.44969041, 24.80797282, 24.45005437, 24.55618552])

In [ ]:
ages2_sample=np.random.choice(ages2,sample_size)
ages2_sample

array([28.09545774, 28.59945894, 27.96221414, 27.2779431 , 28.03867003,
       28.06091064, 28.56581469, 28.59945894, 28.62643408, 27.84689799,
       28.43808446, 27.62280103, 28.02179843, 27.96221414, 28.08001853,
       28.56474195, 29.0927877 , 27.82532864, 27.89962097, 27.6806348 ])

In [ ]:
# summarize to conclude they are from different populations
print('Ages of society 1: mean=%.3f stdv=%.3f' % (np.mean(ages1), np.std(ages1)))
print('Ages of society 2: mean=%.3f stdv=%.3f' % (np.mean(ages2), np.std(ages2)))

Ages of society 1: mean=24.953 stdv=0.477
Ages of society 2: mean=28.091 stdv=0.402


In [ ]:
# stastic of samples from different populations
print('Ages of society 1: mean=%.3f stdv=%.3f' % (np.mean(ages1_sample), np.std(ages1_sample)))
print('Ages of society 2: mean=%.3f stdv=%.3f' % (np.mean(ages2_sample), np.std(ages2_sample)))

Ages of society 1: mean=24.828 stdv=0.317
Ages of society 2: mean=28.143 stdv=0.423


In [ ]:
# function for calculating the t-test for two independent samples 
def independent_ttest(ages1_sample, ages2_sample, alpha):
	#Calculate the means of the two samples
	mean1, mean2 = np.mean(ages1_sample), np.mean(ages2_sample)
	#Calculate the standard errors of the two samples
	ster1, ster2 = sem(ages1_sample), sem(ages2_sample)
	#Calculate the standard error on the difference between the samples
	sed = sqrt(ster1**2.0 + ster2**2.0)
	#Calculate the t statistic
	t_stat = (mean1 - mean2) / sed
	#Calculate the degrees of freedom
	dof = len(ages1_sample) + len(ages2_sample) - 2
	#Calculate the critical value
	cv = t.ppf(1.0 - alpha, dof)
	#Calculate the p-value
	p = (1.0 - t.cdf(abs(t_stat), dof)) * 2.0
	# return everything
	return t_stat, dof, cv, p

In [ ]:
# calculate the t test with Case 1: alpha=0.05 and n=20
alpha = 0.05
t_stat, df, cv, p = independent_ttest(ages1_sample, ages2_sample, alpha)
print('t=%.3f, df=%d, cv=%.3f, p=%.3f' % (t_stat, df, cv, p))
# interpret via critical value
if abs(t_stat) <= cv:
	print('Accept null hypothesis that the sample means of both population are equal.')
else:
	print('Reject the null hypothesis that the sample means of both population are equal.')
# interpret via p-value
if p > alpha:
	print('Accept null hypothesis that the means are equal.')
else:
	print('Reject the null hypothesis that the means are equal.')

t=-27.344, df=38, cv=1.686, p=0.000
Reject the null hypothesis that the sample means of both population are equal.
Reject the null hypothesis that the means are equal.


In case 1, we tested the hypothesis on a sample size of 20 each from both population with alpha=0.05.

When alpha-value = 0.05, or 5%, we can be 95% confident that the sample mean of ages1 is not equal to the sample mean of ages2. We will therefore reject H0 and don't support the claim that the sample mean are from almost same populations but from significantly very different populations. 

In [ ]:
# calculate the t test with Case 2: alpha=0.10, n=20
alpha = 0.10
t_stat, df, cv, p = independent_ttest(ages1_sample, ages2_sample, alpha)
print('t=%.3f, df=%d, cv=%.3f, p=%.3f' % (t_stat, df, cv, p))
# interpret via critical value
if abs(t_stat) <= cv:
	print('Accept null hypothesis that the sample means of both population are equal.')
else:
	print('Reject the null hypothesis that the sample means of both population are equal.')
# interpret via p-value
if p > alpha:
	print('Accept null hypothesis that the means are equal.')
else:
	print('Reject the null hypothesis that the means are equal.')

t=-27.344, df=38, cv=1.304, p=0.000
Reject the null hypothesis that the sample means of both population are equal.
Reject the null hypothesis that the means are equal.


In case 2, we tested the hypothesis on a sample size of 20 each from both population with alpha=0.10.

When alpha-value = 0.10, or 10%, we can be 90% confident that the sample mean of ages1 is not equal to the sample mean of ages2. We will therefore reject H0 and not support the claim that the sample mean are from almost same populations but they are actually from significantly very different populations. 

In [ ]:
# calculate the t test with Case 3: n=20 and alpha=0.01
alpha = 0.01
t_stat, df, cv, p = independent_ttest(ages1_sample, ages2_sample, alpha)
print('t=%.3f, df=%d, cv=%.3f, p=%.3f' % (t_stat, df, cv, p))
# interpret via critical value
if abs(t_stat) <= cv:
	print('Accept null hypothesis that the sample means of both population are equal.')
else:
	print('Reject the null hypothesis that the sample means of both population are equal.')
# interpret via p-value
if p > alpha:
	print('Accept null hypothesis that the means are equal.')
else:
	print('Reject the null hypothesis that the means are equal.')

t=-27.344, df=38, cv=2.429, p=0.000
Reject the null hypothesis that the sample means of both population are equal.
Reject the null hypothesis that the means are equal.


In case 3, we tested the hypothesis on a sample size of 20 each from both population with alpha=0.01.

When alpha-value = 0.01, or 1%, we can be 99% confident that the sample mean of ages1 is not equal to the sample mean of ages2. We will therefore reject H0 and support the claim that the sample mean are not from almost same populations.

If the resulting p-value is more than alpha, then the difference between both observations is statistically significant, and the null hypothesis is accepted. If the resulting p-value is less than alpha, then the null hypothesis is rejected.

In [ ]:
#Form samples of size=45 for ages1 and ages2 to t-test
sample_size=35
ages1_sample=np.random.choice(ages1,sample_size)
ages1_sample

array([24.66437693, 24.44134483, 24.44134483, 24.65641365, 25.29140761,
       24.46351569, 25.45042797, 25.29140761, 25.11720785, 24.65416962,
       25.82990109, 25.37102208, 23.84923065, 24.45005437, 25.25124717,
       24.65641365, 24.62642085, 25.73105397, 24.73591412, 25.45042797,
       24.66437693, 24.65416962, 24.56107079, 25.43270381, 25.81217268,
       25.56688472, 24.56107079, 25.37102208, 24.9936677 , 24.56107079,
       24.86605596, 25.45079536, 25.82990109, 24.55618552, 25.73105397])

In [ ]:
ages2_sample=np.random.choice(ages2,sample_size)
ages2_sample

array([28.44257058, 27.4287409 , 27.74776707, 28.09914986, 28.21174718,
       28.21174718, 27.82807316, 28.59945894, 28.18878189, 28.09545774,
       29.0927877 , 28.25646491, 27.96221414, 28.2933116 , 28.21174718,
       28.15781747, 28.02179843, 27.6806348 , 28.41949171, 28.15008516,
       27.30175183, 27.62280103, 28.75990841, 27.81235752, 28.30860155,
       27.2779431 , 28.25646491, 27.81235752, 28.62643408, 27.82532864,
       27.62280103, 28.44257058, 28.62643408, 27.74776707, 28.56581469])

In [ ]:
# summarize stastic of the samples of two population
print('Ages of society 1: mean=%.3f stdv=%.3f' % (np.mean(ages1_sample), np.std(ages1_sample)))
print('Ages of society 2: mean=%.3f stdv=%.3f' % (np.mean(ages2_sample), np.std(ages2_sample)))

Ages of society 1: mean=25.001 stdv=0.507
Ages of society 2: mean=28.106 stdv=0.412


In [ ]:
# calculate the t test with Case 4: alpha=0.05 and n=35
alpha = 0.05
t_stat, df, cv, p = independent_ttest(ages1_sample, ages2_sample, alpha)
print('t=%.3f, df=%d, cv=%.3f, p=%.3f' % (t_stat, df, cv, p))
# interpret via critical value
if abs(t_stat) <= cv:
	print('Accept null hypothesis that the sample means of both population are equal.')
else:
	print('Reject the null hypothesis that the sample means of both population are equal.')
# interpret via p-value
if p > alpha:
	print('Accept null hypothesis that the means are equal.')
else:
	print('Reject the null hypothesis that the means are equal.')

t=-27.722, df=68, cv=1.668, p=0.000
Reject the null hypothesis that the sample means of both population are equal.
Reject the null hypothesis that the means are equal.


In case 4, we tested the hypothesis on a sample size of 35 each from both population with alpha=0.05.

When alpha-value = 0.05, or 5%, we can be 95% confident that the sample mean of ages1 is not equal to the sample mean of ages2. We will therefore reject H0 and not support the claim that the sample mean are from almost same populations but are from significantly very different populations.

In [ ]:
# calculate the t test with Case 5: alpha=0.10 and n=35
alpha = 0.10
t_stat, df, cv, p = independent_ttest(ages1_sample, ages2_sample, alpha)
print('t=%.3f, df=%d, cv=%.3f, p=%.3f' % (t_stat, df, cv, p))
# interpret via critical value
if abs(t_stat) <= cv:
	print('Accept null hypothesis that the sample means of both population are equal.')
else:
	print('Reject the null hypothesis that the sample means of both population are equal.')
# interpret via p-value
if p > alpha:
	print('Accept null hypothesis that the means are equal.')
else:
	print('Reject the null hypothesis that the means are equal.')

t=-27.722, df=68, cv=1.294, p=0.000
Reject the null hypothesis that the sample means of both population are equal.
Reject the null hypothesis that the means are equal.


In case 5, we tested the hypothesis on a sample size of 35 each from both population with alpha=0.10.

When alpha-value = 0.10, or 10%, we can be 90% confident that the sample mean of ages1 is not equal to the sample mean of ages2. We will therefore reject H0 and support the claim that the sample mean are not from almost same populations but from significantly very different populations.


In [ ]:
# calculate the t test with Case 6: alpha=0.01 and n=35
alpha = 0.05
t_stat, df, cv, p = independent_ttest(ages1_sample, ages2_sample, alpha)
print('t=%.3f, df=%d, cv=%.3f, p=%.3f' % (t_stat, df, cv, p))
# interpret via critical value
if abs(t_stat) <= cv:
	print('Accept null hypothesis that the sample means of both population are equal.')
else:
	print('Reject the null hypothesis that the sample means of both population are equal.')
# interpret via p-value
if p > alpha:
	print('Accept null hypothesis that the means are equal.')
else:
	print('Reject the null hypothesis that the means are equal.')

t=-27.722, df=68, cv=1.668, p=0.000
Reject the null hypothesis that the sample means of both population are equal.
Reject the null hypothesis that the means are equal.


In case 6, we tested the hypothesis on a sample size of 35 each from both population with alpha=0.01.

When alpha-value = 0.01, or 1%, we can be 99% confident that the sample mean of ages1 is not equal to the sample mean of ages2. We will therefore reject H0 and support the claim that the sample mean are from almost same populations.


**Creating the dependent T-test or paired T-test from scratch**

In [ ]:
weight1= 0.5 * randn(24) + 25
len(weight1)

24

In [ ]:
import scipy.stats as stats
weight2=weight1+stats.norm.rvs(scale=5,loc=0.5,size=24)
print(weight2)

[28.26781921 30.02885115 16.47537168 27.51320094 24.84499026 22.63051123
 20.74622167 23.54091476 27.97384091 26.5422408  31.90980699 27.32678812
 18.95963892 24.83439598 22.86550669 30.25551844 26.56196931 22.54965247
 29.54022604 22.66578315 18.81117809 32.48359553 20.33116289 23.16536937]


In [ ]:
# function for calculating the t-test for two dependent samples
def dependent_ttest(weight1_sample, weight2_sample, alpha):
	# calculate means
	mean1, mean2 = np.mean(weight1_sample), np.mean(weight2_sample)
	# number of paired samples
	n = len(weight1_sample)
	# sum squared difference between observations
	d1 = sum([(weight1_sample[i]-weight2_sample[i])**2 for i in range(n)])
	# sum difference between observations
	d2 = sum([weight1_sample[i]-weight2_sample[i] for i in range(n)])
	# standard deviation of the difference between means
	sd = sqrt((d1 - (d2**2 / n)) / (n - 1))
	# standard error of the difference between the means
	sed = sd / sqrt(n)
	# calculate the t statistic
	t_stat = (mean1 - mean2) / sed
	# degrees of freedom
	df = n - 1
	# calculate the critical value
	cv = t.ppf(1.0 - alpha, df)
	# calculate the p-value
	p = (1.0 - t.cdf(abs(t_stat), df)) * 2.0
	# return t value, degree of freedom, critical value and p value
	return t_stat, df, cv, p

In [ ]:
#Form samples of size=20 for weight1 and weight2 to t-test
sample_size=20
weight1_sample=np.random.choice(weight1,sample_size)
weight1_sample
weight2_sample=np.random.choice(weight2,sample_size)
weight2_sample

array([27.97384091, 31.90980699, 27.32678812, 20.33116289, 20.74622167,
       28.26781921, 22.86550669, 24.84499026, 23.16536937, 27.32678812,
       27.51320094, 28.26781921, 22.86550669, 22.54965247, 20.74622167,
       28.26781921, 20.33116289, 30.02885115, 20.74622167, 24.84499026])

In [ ]:
#Null Hypothesis: The sample mean of weight1 population is equal to sample mean of weight2 population
#Alternate Hypothesis: The sample mean of weight1 is different from sample mean of weight2

In [ ]:
# calculate the t test with case 1: n=20, alpha=0.05
alpha = 0.05
t_stat, df, cv, p = dependent_ttest(weight1_sample, weight2_sample, alpha)
print('t=%.3f, df=%d, cv=%.3f, p=%.3f' % (t_stat, df, cv, p))
# interpret via critical value
if abs(t_stat) <= cv:
	print('Accept null hypothesis that the means are equal.')
else:
	print('Reject the null hypothesis that the means are equal.')
# interpret via p-value
if p > alpha:
	print('Accept null hypothesis that the means are equal.')
else:
	print('Reject the null hypothesis that the means are equal.')

t=-0.059, df=19, cv=1.729, p=0.954
Accept null hypothesis that the means are equal.
Accept null hypothesis that the means are equal.


When alpha-value = 0.05, or 5%, we can be 95% confident that the population mean of the two weights are same. We will therefore accept H0 and support the claim. It means there is not much difference between the samples of recent weight and samples of previous weight of the group. The sample size in this case is 20.

In [ ]:
# calculate the t test with Case 2: n=20, alpha=0.01
alpha = 0.01
t_stat, df, cv, p = dependent_ttest(weight1_sample, weight2_sample, alpha)
print('t=%.3f, df=%d, cv=%.3f, p=%.3f' % (t_stat, df, cv, p))
# interpret via critical value
if abs(t_stat) <= cv:
	print('Accept null hypothesis that the means are equal.')
else:
	print('Reject the null hypothesis that the means are equal.')
# interpret via p-value
if p > alpha:
	print('Accept null hypothesis that the means are equal.')
else:
	print('Reject the null hypothesis that the means are equal.')

t=-0.059, df=19, cv=2.539, p=0.954
Accept null hypothesis that the means are equal.
Accept null hypothesis that the means are equal.


When alpha-value = 0.01, or 1% , we can be 99% confident that the population mean of society 1 is equal to the population mean of society 2. We will therefore accept H0 and support the claim that the both the sample means are not from significantly different populations.  The sample size in this case is 20.

There is still 1% chance that our claim is wrong and these two weights have significant difference. Though it is very little that such an error will occur.

In [ ]:
# calculate the t test with Case 3: n=20, alpha=0.10
alpha = 0.10
t_stat, df, cv, p = dependent_ttest(weight1_sample, weight2_sample, alpha)
print('t=%.3f, df=%d, cv=%.3f, p=%.3f' % (t_stat, df, cv, p))
# interpret via critical value
if abs(t_stat) <= cv:
	print('Accept null hypothesis that the means are equal.')
else:
	print('Reject the null hypothesis that the means are equal.')
# interpret via p-value
if p > alpha:
	print('Accept null hypothesis that the means are equal.')
else:
	print('Reject the null hypothesis that the means are equal.')

t=-0.059, df=19, cv=1.328, p=0.954
Accept null hypothesis that the means are equal.
Accept null hypothesis that the means are equal.


When alpha-value = 0.10, or 10%, we can be 90% confident that the population mean of the two weights are same. We will therefore accept H0 and support the claim.  The sample size in this case is 20.

There is still 10% chance that our claim is wrong and these two weights have significant difference. It means there is not much difference between the samples of recent weight and samples of previous weight of the group. or there is a close relationship between the two weights.


In [ ]:
#Form samples of size=40 for weight1 and weight2 to t-test
sample_size=40
weight1_sample=np.random.choice(weight1,sample_size)
weight1_sample
weight2_sample=np.random.choice(weight2,sample_size)
weight2_sample

array([32.48359553, 22.66578315, 18.95963892, 24.83439598, 26.56196931,
       24.84499026, 20.33116289, 29.54022604, 24.84499026, 27.51320094,
       18.95963892, 16.47537168, 18.95963892, 28.26781921, 28.26781921,
       30.25551844, 24.84499026, 31.90980699, 18.95963892, 29.54022604,
       22.63051123, 26.56196931, 28.26781921, 27.32678812, 18.95963892,
       27.32678812, 27.51320094, 18.95963892, 30.25551844, 32.48359553,
       22.66578315, 24.83439598, 30.02885115, 24.84499026, 23.54091476,
       27.51320094, 16.47537168, 16.47537168, 31.90980699, 22.86550669])

In [ ]:
# calculate the t test with case 4: n=40, alpha=0.05
alpha = 0.05
t_stat, df, cv, p = dependent_ttest(weight1_sample, weight2_sample, alpha)
print('t=%.3f, df=%d, cv=%.3f, p=%.3f' % (t_stat, df, cv, p))
# interpret via critical value
if abs(t_stat) <= cv:
	print('Accept null hypothesis that the means are equal.')
else:
	print('Reject the null hypothesis that the means are equal.')
# interpret via p-value
if p > alpha:
	print('Accept null hypothesis that the means are equal.')
else:
	print('Reject the null hypothesis that the means are equal.')

t=0.076, df=39, cv=1.685, p=0.939
Accept null hypothesis that the means are equal.
Accept null hypothesis that the means are equal.


When alpha-value = 0.05, or 5%, we can be 95% confident that the sample mean of the two weights are same. We will therefore accept H0 and support the claim. It means there is not much difference between the samples of recent weight and samples of previous weight of the group.  The sample size in this case is 40.

In [ ]:
# calculate the t test with Case 5: n=40, alpha=0.01
alpha = 0.01
t_stat, df, cv, p = dependent_ttest(weight1_sample, weight2_sample, alpha)
print('t=%.3f, df=%d, cv=%.3f, p=%.3f' % (t_stat, df, cv, p))
# interpret via critical value
if abs(t_stat) <= cv:
	print('Accept null hypothesis that the means of thr population are equal.')
else:
	print('Reject the null hypothesis that the means are equal.')
# interpret via p-value
if p > alpha:
	print('Accept null hypothesis that the means are equal.')
else:
	print('Reject the null hypothesis that the means are equal.')

t=0.076, df=39, cv=2.426, p=0.939
Accept null hypothesis that the means are equal.
Accept null hypothesis that the means are equal.


When alpha-value = 0.01, or 1% , we can be 99% confident that the sample mean of society 1 is equal to the sample mean of society 2. We will therefore accept H0 and support the claim that the both the sample means are not from significantly different populations. The sample size in this case is 40.

There is still 1% chance that our claim is wrong and these two weights have significant difference. Though it is very little that such an error will occur.


In [ ]:
# calculate the t test with Case 6: n=20, alpha=0.10
alpha = 0.10
t_stat, df, cv, p = dependent_ttest(weight1_sample, weight2_sample, alpha)
print('t=%.3f, df=%d, cv=%.3f, p=%.3f' % (t_stat, df, cv, p))
# interpret via critical value
if abs(t_stat) <= cv:
	print('Accept null hypothesis that the means are equal.')
else:
	print('Reject the null hypothesis that the means are equal.')
# interpret via p-value
if p > alpha:
	print('Accept null hypothesis that the means are equal.')
else:
	print('Reject the null hypothesis that the means are equal.')

t=0.076, df=39, cv=1.304, p=0.939
Accept null hypothesis that the means are equal.
Accept null hypothesis that the means are equal.


When alpha-value = 0.10, or 10%, we can be 90% confident that the population mean of the two weights are same. We will therefore accept H0 and support the claim. The sample size in this case is 40.

There is still 10% chance that our claim is wrong and these two weights have significant difference. It means there is not much difference between the samples of recent weight and samples of previous weight of the group. or there is a close relationship between the two weights.


**ANOVA Test**


The purpose of a one-way analysis of variance (one-way ANOVA) is to compare the means of two or more groups (the independent variable) on one dependent variable to see if the group means are significantly different from each other. ANOVA is a statistical test that assumes that the mean across 2 or more groups are equal. If the evidence suggests that this is not the case, the null hypothesis is rejected and at least one data sample has a different distribution.

In [ ]:
# Analysis of Variance test
from scipy.stats import f_oneway

# Generating three independent samples with Gaussian distribution.
# The independence of sample and them being Gaussian distributed fulfills the basic assumption required for Student's T test.
# We are expecting the Anova test to give us the result that they are from the same population
ages1 = 0.5 * randn(100) + 25
ages3 = 0.5 * randn(50) + 25
ages2 = 0.5 * randn(45) + 25

#Form samples of size=25 for ages1 and ages2 and ages3
sample_size=25
ages1_sample=np.random.choice(ages1,sample_size)
ages1_sample
ages2_sample=np.random.choice(ages2,sample_size)
ages2_sample
ages3_sample=np.random.choice(ages3,sample_size)
ages3_sample

array([24.77084898, 24.58827805, 24.67670889, 24.94930961, 25.46681481,
       24.60634323, 24.79489159, 24.91988094, 24.98503206, 24.95870238,
       24.11811264, 25.44796074, 24.96197452, 24.58827805, 24.48167207,
       25.38364681, 24.71398706, 25.12346137, 24.95870238, 25.37518741,
       24.98503206, 24.58827805, 24.59772921, 24.95870238, 24.82917837])

In [ ]:
#Checking if our dataset samples are Gaussian which is a requirement for Student's T-test
from scipy.stats import normaltest
stat, p=normaltest(ages1)
alpha=0.1
if p>alpha:
  print("Slope is Gaussian for ages1")
else:
  print("Slope is not Gaussian")
stat, p=normaltest(ages2)
alpha=0.1
if p>alpha:
  print("Slope is Gaussian for ages2")
else:
  print("Slope is not Gaussian")
stat, p=normaltest(ages3)
alpha=0.1
if p>alpha:
  print("Slope is Gaussian for ages3")
else:
  print("Slope is not Gaussian")

Slope is Gaussian for ages1
Slope is Gaussian for ages2
Slope is Gaussian for ages3


In [ ]:
#   H0: All paired sample distributions are equal.
#   H1: One or more paired sample distributions are not equal.


In [ ]:
#Comparing samples
stat, p = f_oneway(ages1_sample, ages2_sample, ages3_sample) 
print('Statistics=%.3f, p=%.3f' % (stat, p))

Statistics=0.394, p=0.676


In [ ]:
#Interpreting the samples. Case 1: n=25, alpha=0.05

alpha = 0.05
if p > alpha: 
  print('All paired sample distributions are equal. We accept H0')
else:
  print('One or more paired sample distributions are not equal. We reject H0')

All paired sample distributions are equal. We accept H0


When alpha-value = 0.05, or 5%, we can be 95% confident that the sample mean of the three ages population are same. We will therefore accept H0 and support the claim that the paired sample distributions are equal. The sample size in this case is 25.

There is still 10% chance that our claim is wrong and these three weights have significant difference and aren't paired otherwise known as the Type 2 error. Type 2 error is the non-rejection of a false null hypothsis. The conclusion is that there is not much difference between the samples of the population of ages mentioned.

In [ ]:
#Interpreting the samples. Case 2: n=25, alpha=0.03

alpha = 0.03
if p > alpha: 
  print('All paired sample distributions are equal. We accept H0')
else:
  print('One or more paired sample distributions are not equal. We reject H0')

All paired sample distributions are equal. We accept H0


When alpha-value = 0.01, or 1%, we can be 99% confident that the sample mean of the three ages population are same. We will therefore accept H0 and support the claim that the paired sample distributions are equal. The sample size in this case is 25.

There is still 1% chance that our claim is wrong and these three weights have significant difference and aren't paired. The conclusion is that there is not much difference between the samples of the population of ages mentioned.



In [ ]:
#Interpreting the samples. Case 2: n=25, alpha=0.1

alpha = 0.1
if p > alpha: 
  print('All paired sample distributions are equal. We accept H0')
else:
  print('One or more paired sample distributions are not equal. We reject H0')

All paired sample distributions are equal. We accept H0


When alpha-value = 0.1, or 10%, we can be 90% confident that the sample mean of the three ages population are same. We will therefore accept H0 and support the claim that the paired sample distributions are equal. The sample size in this case is 25.

There is still 10% chance that our claim is wrong and these three weights have significant difference and aren't paired. The conclusion is that there is not much difference between the samples of the population of ages mentioned.


In [ ]:
#Form samples of size=35 for ages1 and ages2 and ages3
sample_size=35
ages1_sample=np.random.choice(ages1,sample_size)
ages1_sample
ages2_sample=np.random.choice(ages2,sample_size)
ages2_sample
ages3_sample=np.random.choice(ages3,sample_size)
ages3_sample

array([24.94930961, 24.94930961, 25.46681481, 24.59772921, 24.22364706,
       25.10821713, 24.71398706, 24.70528516, 24.11811264, 24.44661057,
       25.19151343, 25.01500576, 24.58827805, 25.71158859, 24.95870238,
       24.83656696, 25.22011725, 25.12346137, 24.77316644, 25.22011725,
       24.37402128, 25.71158859, 24.25967269, 24.67670889, 24.51866872,
       24.58827805, 25.37518741, 24.67670889, 25.36114006, 24.98503206,
       25.22011725, 24.74263254, 24.25967269, 24.98503206, 25.10651286])

In [ ]:
#Comparing samples
stat, p = f_oneway(ages1_sample, ages2_sample, ages3_sample) 
print('Statistics=%.3f, p=%.3f' % (stat, p))

Statistics=3.316, p=0.040


In [ ]:
#Interpreting the samples. Case 4: n=35, alpha=0.05

alpha = 0.05
if p > alpha: 
  print('All paired sample distributions are equal. We accept H0')
else:
  print('One or more paired sample distributions are not equal. We reject H0')

One or more paired sample distributions are not equal. We reject H0


When alpha-value = 0.05, or 5%, we can be 95% confident that the sample mean of the three ages population are same. We will therefore accept H0 and support the claim that the paired sample distributions are equal. The sample size in this case is 35.

There is still 5% chance that our claim is wrong and these three weights have significant difference and aren't paired. The conclusion is that there is not much difference between the samples of the population of ages mentioned as expected.

In [ ]:
#Interpreting the samples. Case 5: n=35, alpha=0.03

alpha = 0.03
if p > alpha: 
  print('All paired sample distributions are equal. We accept H0')
else:
  print('One or more paired sample distributions are not equal. We reject H0')

All paired sample distributions are equal. We accept H0


When alpha-value = 0.03, or 3%, we can be 97% confident that the sample mean of the three ages population are same. We will therefore accept H0 and support the claim that the paired sample distributions are equal. The sample size in this case is 35.

There is still 3% chance that our claim is wrong and these three weights have significant difference and aren't paired. The conclusion is that there is not much difference between the samples of the population of ages mentioned as expected.

In [ ]:
#Interpreting the samples. Case 6: n=35, alpha=0.1

alpha = 0.1
if p > alpha: 
  print('All paired sample distributions are equal. We accept H0')
else:
  print('One or more paired sample distributions are not equal. We reject H0')

One or more paired sample distributions are not equal. We reject H0


When alpha-value = 0.1, or 10%, we can be 90% confident that the sample mean of the three ages population are same. We will therefore accept H0 and support the claim that the paired sample distributions are equal. The sample size in this case is 35.

There is still 10% chance that our claim is wrong and these three weights have significant difference and aren't paired. The conclusion is that there is not much difference between the samples of the population of ages mentioned as expected.